<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cards')->truncate();
        DB::table('promocodes')->truncate();
        DB::table('promocode_usages')->truncate();
        DB::table('provider_devices')->truncate();
        DB::table('provider_documents')->truncate();
        DB::table('provider_profiles')->truncate();
        DB::table('provider_services')->truncate();
        DB::table('request_filters')->truncate();
        DB::table('user_request_payments')->truncate();
        DB::table('user_request_ratings')->truncate();
        DB::table('user_requests')->truncate();
        DB::table('users')->truncate();
        DB::table('users')->insert([[
            'first_name' => 'Appoets',
            'last_name' => 'Demo',
            'email' => 'demo@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Emilia',
            'last_name' => 'Epps',
            'email' => 'emilia@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Perry',
            'last_name' => 'Kingsley',
            'email' => 'perry@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Joseph',
            'last_name' => 'Garrison',
            'email' => 'joseph@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Ella',
            'last_name' => 'Morrissey',
            'email' => 'morrissey@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Elizabeth',
            'last_name' => 'Forshee',
            'email' => 'elizabeth@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Douglas',
            'last_name' => 'Arce',
            'email' => 'douglas@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Sara',
            'last_name' => 'Nixon',
            'email' => 'sara@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Edward',
            'last_name' => 'Jett',
            'email' => 'edward@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Marilyn',
            'last_name' => 'Bradley',
            'email' => 'marilyn@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Herman',
            'last_name' => 'Thompson',
            'email' => 'herman@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Darrin',
            'last_name' => 'Neely',
            'email' => 'darrin@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Ralph',
            'last_name' => 'Vaughn',
            'email' => 'ralph@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Arturo',
            'last_name' => 'Gibson',
            'email' => 'arturo@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Kevin',
            'last_name' => 'Delacruz',
            'email' => 'kevin@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Catherine',
            'last_name' => 'Ferguson',
            'email' => 'catherine@appoets.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/?34733',
        ]]);

        DB::table('providers')->truncate();
        DB::table('providers')->insert([[
            'first_name' => 'Appoets',
            'last_name' => 'Demo',
            'email' => 'demo@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Thomas',
            'last_name' => 'Jenkins',
            'email' => 'thomas@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Rachel',
            'last_name' => 'Burns',
            'email' => 'rachel@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Lorraine',
            'last_name' => 'Harris',
            'email' => 'lorraine@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Adam',
            'last_name' => 'Wagner',
            'email' => 'adam@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Christine',
            'last_name' => 'Forshee',
            'email' => 'christine@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Logan',
            'last_name' => 'Arce',
            'email' => 'logan@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Joe',
            'last_name' => 'Demo',
            'email' => 'joe@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Price',
            'last_name' => 'Jett',
            'email' => 'price@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Lloyd',
            'last_name' => 'Bradley',
            'email' => 'lloyd@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Evans',
            'last_name' => 'Thompson',
            'email' => 'evans@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Jerry',
            'last_name' => 'Neely',
            'email' => 'jerry@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Teresa',
            'last_name' => 'Vaughn',
            'email' => 'teresa@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Sarah',
            'last_name' => 'Gibson',
            'email' => 'sarah@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Regina',
            'last_name' => 'Delacruz',
            'email' => 'regina@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Ferguson',
            'email' => 'anthony@appoets.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/?34733',
        ]]);

        DB::table('provider_services')->truncate();
        DB::table('provider_services')->insert([[
            'provider_id' => 1,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 2,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 3,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 4,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 5,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 6,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 7,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 8,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 9,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 10,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 11,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 12,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 13,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 14,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 15,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 16,
            'service_type_id' => 1,
            'status' => 'active',
            'service_number' => '4ppo3ts',
            'service_model' => 'Audi R8',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]]);
    }
}
